---
- name: Gather Cisco router version
  hosts: routers
  gather_facts: no
  #vars_files:
   # - routers.yml   # <— pulls in your variables

  tasks:
    - name: Run "show version" command
      ios_command:
        commands:
          - show version
      register: output

    - name: Display version output
      debug:
        msg: "{{ output.stdout[0] }}"